### ISSUE TITLE
Promotional participation

### ISSUE THREAD

**Issue by keilw** [Tenkiv/Physikal#3] opened 2017-07-11 16:08 UTC
I thought, I'll open a new ticket instead of discussing on a different topic.

I plan to propose a talk related to Kotlin and Physikal at [JVM-Con 2017](http://jvm-con.de/) in November
A few weeks earlier there's [KotlinConf 2017](https://www.kotlinconf.com/) in San Francisco.
Maybe keep that and JavaOne a month earlier on the radar, because they all happen in Silicon Valley.

[DevoXX US](http://devoxx.us/) should also happen again in Silicon Valley or somewhere else in the US (if they changed the host city for some reason) There is no CFP yet.

Given the Sustainable nature of your projects, aside from IT events, did you hear about [Sustania](http://www.sustainia.me/solutions)?

I was in Copenhagen for one of the first Sustania Award ceremonies with Arnold Schwarzenegger and others. It seems, they do not hold them every year, but you can nominate your solutions you think are worthy there and should provide great visibility.

About meeting in person, a possible chance could be the "Java Community BBQ". It is usually for Java Champions and interested members of e.g. the JCP/EC on Friday before JavaOne. Held in Redwood or Belmont near Oracle HQ. I cannot promise for sure, but as @otaviojava and several others are Java Champions, if one of them invited you, it seems possible. I also had @atsticks, the Spec Lead of JSR 354 join although he is not on the EC or a Java Champion at this point, so it could be possible, as long as you're invited and it does not require a JavaOne pass. Otherwise there could be an opportunity in town if it was convenient for you to meet us on a less formal basis between Thursday Sep 28 and Oct 5.

Cheers,
Werner

**Comment by zjuhasz** [comment] 2017-07-11 23:58
We're already registered for KotlinConf (a bit more affordable than JavaOne). Never heard of Sustania, we'll look into it. 

The only thing on my schedule around the dates you're mentioning is KotlinConf, so whatever time is most convenient for you and others to meet up in the SF bay area should work for @ejberry and me. The Java Community BBQ does sound like it would be pretty cool if you could get us in though  ;)

A company that manufactures our solar collector prototypes has their main R&D facility in Crimmitschau, so we go to Germany several times a year to meet with them (next trip we'll likely also be meeting with another manufacturer in Amsterdam). If you do end up giving a talk at JVM-Con that involves Physikal we might be able to attend if we can work out the timing with some of our other meetings in the area, so please keep us up to date with that.

Also wanted to thank you for your interest and for sharing our work with your colleagues, very exciting for us!

**Comment by keilw** [comment] 2017-07-12 09:43
Thanks for the update. It would be great to do a joint presentation at JVMCon. Unlike JavaOne or DevoXX at least hotel and everything is taken care of for speakers (even co-speakers)
I am waiting for feedback by Heather/PMO on a meeting spot for Expert Groups we usually got in the Hilton in the last couple of years. That does not mandate a conference pass, so e.g. EG members in town who are not at JavaOne were able to participate. If they do not change that, you would be welcome to join us there. Close To JavaOne the annual SI Conference takes place, and in Summer 2018 the SI Standard is scheduled to undergo some changes in its definition. We plan an update to the JSR around then and JavaOne would likely be our Kick-Off Meeting: https://github.com/unitsofmeasurement/unit-api/milestone/2

**Comment by ejberry** [comment] 2017-07-14 02:38
We can definitely go to the Hilton for the JavaOne expert groups if they still don't require a pass. Keep us up to date if/where that's going to happen.
JVMCon sounds great. Let us know the status of the presentation application and if we need to contact anyone.

**Comment by keilw** [comment] 2017-08-02 12:52
Hi, I will soon propose a session to JVM-Con http://jvm-con.de/call-for-papers/ and if you're happy to try the same JavaLand 2018 both in Cologne (that CVP actually ends a bit sooner, a week from now: https://www.javaland.eu/de/home/) Do you have suggestions for an abstract you would like to see mentioned?

**Comment by ejberry** [comment] 2017-08-09 07:27
Sorry for taking a bit to get back to you on this, things have been a bit hectic. As for an abstract for JVM-Con, our project can be summarized as reducing code verbosity with extensions, operator overloads, and infix functions. If there needs to be something shorter, longer, or more formalized, we can definitely provide you with that.

**Comment by keilw** [comment] 2017-08-09 09:56
Thanks, Can you share any of the concrete projects and environmental efforts. E.g. https://www.kickstarter.com/projects/tenkiv/tekdaqc-robust-precise-data-acquisition-and-contro/description says:
>Comes with a Java JAR library to interact with the board

So does Java or Kotlin also run on the devices or are they mainly used for data analysis? The JUGs running JavaLand (its CFP ends tomorrow at midnight CET) sounded interested in the idea, too. I can't say, if a proposal would be approved but it's worth trying. For JVM-Con I am a member of the AdBoard, so I have at least one voice deciding over topics.

**Comment by zjuhasz** [comment] 2017-08-09 17:49
Let me give a brief description of what we work on that will hopefully make some sense in the context of the JVM. Basically we've developed a new kind of solar power system focused on cost-effectiveness and scalability. It's not just a new solar panel but a complete and extensible integrated system (everything for collecting, moving, converting, and storing energy). The system is fully automated so we needed a data acquisition system to get collect data from all the sensors throughout the system. The problem is existing data acquisition systems with the quality and robustness we needed cost over $10,000. This is why we made the Tekdaqc early on in our development process, so we could have the exact data acquisition system we needed for a vary low cost. 

The Tekdaqc firmware is written completely in C https://github.com/Tenkiv/Tekdaqc-Firmware. But all the automation code runs on a separate computer, this is where we decide how to fill panels, when to store energy, what the power, and all the details associated with these things like what valves need to be switched, pump settings, etc. It's challenging because a one installation of our system can be very different from another, using different modules (what we call the energy conversion devices), different number of thermal circuits, variable number of collectors, and more. So the control software has to be very adaptable to match the adaptability of the hardware platform. 

The control software itself is written completely in Kotlin. We call the control software Nexus Brain and unfortunately at this time it is not open source, but hopefully it will be eventually. A big component of Nexus Brain (our generic abstraction for handling data acquisition and control) is open source https://github.com/Tenkiv/Daqc-Tools although it is not at all ready to be viewed publicly. By the way Nexus Brain and daqc tools both heavily use units of measurement, the physikal extensions library used to be built into Nexus Brain until we recently made it its own library.

The Tekdaqc and the Java library for using it https://github.com/Tenkiv/Tekdaqc-Java-Core-Library are currently used for many projects, for example at places like NASA and ETH Zurich. Our complete solar power system is not yet in production, our first pilot plant will be in Afghanistan and installation should begin early next year. It will be using pre-production solar panels and will be used for making clean water.

**Comment by keilw** [comment] 2017-08-10 13:13
Thanks a lot for the detailed outline. I guess I can factor it into an abstract for JavaLand which is due later tonight. About JVM-Con (the conference with a loger CFP but it happens this November, not in Q1/18) we're also looking for interesting keynote speakers and topics. Would you consider something like that, too? 
This was one of the keynotes at DWX (by the same organizer) http://www.developer-week.de/Programm/Veranstaltung/(event)/21314 by Microsoft's Jennifer Marsman. I am confident, especially with your software being used by NASA, ETH, etc. that you could also be a good keynote candidate for JVM-Con, if you feel comfortable doing that or have done so in the past.

**Comment by keilw** [comment] 2017-08-10 22:04
Hi, hope I extracted your details well, I just submitted a proposal to JavaLand with @zjuhasz and @ejberry as proposed co-speakers. I'll send you the abstract text by mail. Not sure, if JavaLand sends confirmation mails or wants email confirmations, but just to let you know, if either of you hear from them.

**Comment by keilw** [comment] 2017-08-15 15:50
Hi, it was confirmed, there is no dedicated meeting room for Expert Groups this year. So depending on your own availability, some time between Sep 28 (when the EC F2F starts) and Oct 5 (the last day of JavaOne) I guess we'll find a location. This could be the JUG Leader BBQ if that's open enough (PMO will share an invite for that, if it is EventBrite and not restricted to JCP or JUG membership, then it should be accessible to other members of the community) 
Two years ago we met @msgilligan who helped a lot with the Groovy port of JSR 354 and he's also interested in Kotlin or using it in his projects already. I guess you guys might like to meet if you can. 
So let's wait for the BBQ announcement and then decide what's the best place and time to meet in those 7 days.

**Comment by ejberry** [comment] 2017-08-17 22:56
We should be able to meet up anytime in SF during that week. Hope to see you there soon.

**Closed** 2017-09-15 01:37 UTC
Labels: discussion
